"""
WW1 ECONOMY — PRODUCTION SYSTEM
---------------------------------
Monthly production tick for the WW1 scenario.

This module runs once per in-game month and:
  1. Fetches all completed AND ACTIVE buildings (consumption system flips
     ``is_active`` BEFORE production runs; inactive buildings produce
     nothing this month).
  2. For each Tier 1 building, validates that the province resource still
     matches the building resource.  Mismatches are logged and skipped.
  3. Adds the building's monthly production to the country's storage,
     EXCEPT:
       • Horses (Ranch) — never stored; daily_income only.
       • Textiles (Textile Mill) — never stored; daily_income only.
       • Gold (Precious Mine on a gold province) — +25 gold/month
         deposited DIRECTLY to the country treasury.
       • Gems (Precious Mine on a gems province) — +30 gold/month
         deposited DIRECTLY to the country treasury.
  4. Calculates the total daily_income generated by all active buildings.

The function returns a detailed ProductionReport so the game layer can
inspect what happened.  When a TreasurySystem is supplied, gold and gems
mines are credited to the treasury immediately; otherwise the gold values
are only reported (legacy behaviour for the original demo).

Province → Country mapping
--------------------------
The buildings table includes a country_id column so the production system
can route resources to the right country without an external lookup.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ww1_economy.db              import EconomyDB
from ww1_economy.storage_system  import StorageSystem
from ww1_economy.treasury_system import TreasurySystem
from ww1_economy.resources       import (
    BuildingType,
    BUILDING_CONFIGS,
    TIER1_BUILDING_TYPES,
    NON_STORABLE_PRODUCTS,
    get_config,
    resolve_tier1_production_resource,
)


# ---------------------------------------------------------------------------
# Per-spec gold deposit amounts for the Precious Mine
# ---------------------------------------------------------------------------
# These mirror the spec exactly:
#   Gold Mine → +25 gold/month
#   Gems Mine → +30 gold/month
# The BuildingConfig.gold_to_treasury_monthly is the gold-branch number
# (25.0).  The gems branch uses GEMS_GOLD_PER_MONTH directly.
GEMS_GOLD_PER_MONTH: float = 30.0


# ---------------------------------------------------------------------------
# Production report data structures
# ---------------------------------------------------------------------------

@dataclass
class CountryProduction:
    """Aggregated production result for a single country in one monthly tick."""
    country_id:           str
    resources_added:      dict[str, int]  = field(default_factory=dict)
    income_only:          dict[str, int]  = field(default_factory=dict)  # horses / textiles
    gold_to_treasury:     float           = 0.0   # Precious Mine gold output (gold + gems)
    daily_income_total:   float           = 0.0   # Sum of ACTIVE buildings' daily incomes
    buildings_processed:  int             = 0
    buildings_skipped:    int             = 0
    buildings_inactive:   int             = 0


@dataclass
class ProductionReport:
    """Full monthly production report for a scenario tick."""
    server_id:   str
    scenario_id: str
    by_country:  dict[str, CountryProduction]  = field(default_factory=dict)
    skipped:     list[dict]                    = field(default_factory=list)

    def summary(self) -> dict:
        """Return a JSON-serialisable summary of this report."""
        return {
            "server_id":   self.server_id,
            "scenario_id": self.scenario_id,
            "countries": {
                cid: {
                    "resources_added":     cp.resources_added,
                    "income_only":         cp.income_only,
                    "gold_to_treasury":    cp.gold_to_treasury,
                    "daily_income_total":  cp.daily_income_total,
                    "buildings_processed": cp.buildings_processed,
                    "buildings_skipped":   cp.buildings_skipped,
                    "buildings_inactive":  cp.buildings_inactive,
                }
                for cid, cp in self.by_country.items()
            },
            "skipped": self.skipped,
        }


# ---------------------------------------------------------------------------
# ProductionSystem
# ---------------------------------------------------------------------------

class ProductionSystem:
    """
    Runs monthly production ticks for the WW1 economy scenario.

    Parameters
    ----------
    db       : EconomyDB         — shared database instance.
    storage  : StorageSystem     — used to add resources to country storage.
    treasury : TreasurySystem | None
        If provided, gold and gems mines deposit gold directly to the
        country treasury during the monthly tick.  If omitted the report
        still reports the gold amount under ``gold_to_treasury`` so a
        legacy caller can apply it manually.
    """

    def __init__(
        self,
        db:       EconomyDB,
        storage:  StorageSystem,
        treasury: TreasurySystem | None = None,
    ) -> None:
        self._db       = db
        self._storage  = storage
        self._treasury = treasury

    # ------------------------------------------------------------------
    # Main tick
    # ------------------------------------------------------------------

    def run_monthly_production(
        self,
        server_id:   str,
        scenario_id: str,
    ) -> ProductionReport:
        """
        Execute one in-game month of production for every completed building
        in the scenario.

        Steps
        -----
        1. Fetch all completed buildings (server_id + scenario_id).
        2. For each building:
           a. Look up the BuildingConfig.
           b. Tier 1 — validate province resource matches; skip on mismatch.
           c. Add monthly_production to country storage.
           d. For Precious Mine + gold resource — add gold to treasury report.
           e. Accumulate daily_income for this country.
        3. Return a ProductionReport.

        The caller is responsible for:
          • Depositing ``gold_to_treasury`` values into each country's treasury.
          • Applying ``daily_income_total`` to each country's daily income.
        """
        report    = ProductionReport(server_id=server_id, scenario_id=scenario_id)
        buildings = self._db.get_completed_buildings(server_id, scenario_id)

        for brow in buildings:
            country_id    = brow["country_id"]
            province_id   = brow["province_id"]
            building_type = brow["building_type"]
            resource_type = brow.get("resource_type")   # stored province resource
            is_active     = bool(brow.get("is_active", 1))

            cfg = get_config(building_type)

            # Ensure we have a CountryProduction entry
            if country_id not in report.by_country:
                report.by_country[country_id] = CountryProduction(country_id=country_id)
            cp = report.by_country[country_id]

            # ----------------------------------------------------------
            # INACTIVE buildings produce nothing and earn no income.
            # The consumption system flips this flag BEFORE production.
            # ----------------------------------------------------------
            if not is_active:
                cp.buildings_inactive += 1
                report.skipped.append({
                    "province_id":   province_id,
                    "building_type": building_type,
                    "reason":        "Inactive (consumption shortfall this month).",
                })
                continue

            # ----------------------------------------------------------
            # Tier 1 — resource validation
            # ----------------------------------------------------------
            if cfg.is_tier1:
                if resource_type is None:
                    skip_reason = (
                        f"Tier 1 building '{building_type}' in province "
                        f"'{province_id}' has no resource_type set."
                    )
                    report.skipped.append({
                        "province_id":   province_id,
                        "building_type": building_type,
                        "reason":        skip_reason,
                    })
                    cp.buildings_skipped += 1
                    continue

                if resource_type not in cfg.allowed_resources:
                    skip_reason = (
                        f"Resource mismatch: '{building_type}' in province "
                        f"'{province_id}' has resource_type='{resource_type}' "
                        f"but building allows {sorted(cfg.allowed_resources)}."
                    )
                    report.skipped.append({
                        "province_id":   province_id,
                        "building_type": building_type,
                        "reason":        skip_reason,
                    })
                    cp.buildings_skipped += 1
                    continue

                # Precious Mine: gold AND gems both go to treasury
                if BuildingType(building_type) == BuildingType.PRECIOUS_MINE:
                    if resource_type == "gold":
                        # +25 gold/month to treasury
                        gold_amount = float(cfg.gold_to_treasury_monthly)
                    else:  # gems
                        # +30 gold/month to treasury (per spec)
                        gold_amount = GEMS_GOLD_PER_MONTH
                    cp.gold_to_treasury += gold_amount
                    if self._treasury is not None and gold_amount > 0:
                        self._treasury.deposit(
                            server_id, scenario_id, country_id, gold_amount
                        )
                else:
                    # Standard Tier 1 — produce province resource
                    prod_resource = resource_type
                    amount        = cfg.monthly_production

                    if prod_resource in NON_STORABLE_PRODUCTS:
                        # horses (Ranch) — daily_income only, no storage
                        cp.income_only[prod_resource] = (
                            cp.income_only.get(prod_resource, 0) + amount
                        )
                    else:
                        self._storage.add(
                            server_id, scenario_id, country_id,
                            prod_resource, amount,
                        )
                        cp.resources_added[prod_resource] = (
                            cp.resources_added.get(prod_resource, 0) + amount
                        )

            # ----------------------------------------------------------
            # Tier 2 — always valid (no resource dependency)
            # ----------------------------------------------------------
            else:
                if cfg.production_resource is not None:
                    prod_resource = cfg.production_resource
                    amount        = cfg.monthly_production

                    if prod_resource in NON_STORABLE_PRODUCTS:
                        # textiles (Textile Mill) — daily_income only, no storage
                        cp.income_only[prod_resource] = (
                            cp.income_only.get(prod_resource, 0) + amount
                        )
                    else:
                        self._storage.add(
                            server_id, scenario_id, country_id,
                            prod_resource, amount,
                        )
                        cp.resources_added[prod_resource] = (
                            cp.resources_added.get(prod_resource, 0) + amount
                        )

            # ----------------------------------------------------------
            # Daily income — only ACTIVE buildings contribute.
            # ----------------------------------------------------------
            cp.daily_income_total   += cfg.daily_income
            cp.buildings_processed  += 1

        return report

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    def get_country_income_from_buildings(
        self,
        server_id:   str,
        scenario_id: str,
        country_id:  str,
    ) -> float:
        """
        Calculate the total daily income from all completed buildings owned
        by a country, without running a full production tick.
        """
        total = 0.0
        for row in self._db.get_buildings_by_country(server_id, scenario_id, country_id):
            if row["is_completed"]:
                cfg    = get_config(row["building_type"])
                total += cfg.daily_income
        return round(total, 4)

    def get_monthly_production_preview(
        self,
        server_id:   str,
        scenario_id: str,
        country_id:  str,
    ) -> dict:
        """
        Return a preview of what would be produced next month for a country,
        without writing anything to the database.

        Reflects the new rules:
          • horses & textiles never accrue to storage
          • gold AND gems mines deposit gold to treasury (not storage)
          • only ACTIVE buildings contribute to daily_income
        """
        preview:     dict[str, int]  = {}
        income_only: dict[str, int]  = {}
        gold_income: float           = 0.0
        daily_income: float          = 0.0

        for row in self._db.get_buildings_by_country(server_id, scenario_id, country_id):
            if not row["is_completed"]:
                continue
            if not bool(row.get("is_active", 1)):
                continue
            cfg            = get_config(row["building_type"])
            resource_type  = row.get("resource_type")
            daily_income  += cfg.daily_income

            if cfg.is_tier1:
                if resource_type and resource_type in cfg.allowed_resources:
                    if BuildingType(row["building_type"]) == BuildingType.PRECIOUS_MINE:
                        if resource_type == "gold":
                            gold_income += cfg.gold_to_treasury_monthly
                        else:
                            gold_income += GEMS_GOLD_PER_MONTH
                    elif resource_type in NON_STORABLE_PRODUCTS:
                        income_only[resource_type] = (
                            income_only.get(resource_type, 0) + cfg.monthly_production
                        )
                    else:
                        preview[resource_type] = (
                            preview.get(resource_type, 0) + cfg.monthly_production
                        )
            else:
                if cfg.production_resource:
                    if cfg.production_resource in NON_STORABLE_PRODUCTS:
                        income_only[cfg.production_resource] = (
                            income_only.get(cfg.production_resource, 0)
                            + cfg.monthly_production
                        )
                    else:
                        preview[cfg.production_resource] = (
                            preview.get(cfg.production_resource, 0) + cfg.monthly_production
                        )

        return {
            "country_id":          country_id,
            "monthly_resources":   preview,
            "income_only":         income_only,
            "gold_to_treasury":    gold_income,
            "daily_income_total":  round(daily_income, 4),
        }
