"""
WW1 ECONOMY — PRODUCTION SYSTEM
---------------------------------
Monthly production tick for the WW1 scenario.

This module runs once per in-game month and:
  1. Fetches all completed buildings (server_id + scenario_id filtered).
  2. For each Tier 1 building, validates that the province resource still
     matches the building resource.  Mismatches are logged and skipped.
  3. Adds the building's monthly production to the country's storage.
  4. Calculates the total daily_income generated by all buildings.
  5. Handles the Precious Mine special case:
     - Gold province  → +25 gold/month added to treasury report
                        (not stored; caller deposits to economy system)
     - Gems province  → +10 gems/month added to storage

The function returns a detailed ProductionReport so the game layer can
apply treasury income and notify players without any tight coupling.

Province → Country mapping
--------------------------
The buildings table includes a country_id column so the production system
can route resources to the right country without an external lookup.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ww1_economy.db        import EconomyDB
from ww1_economy.storage_system import StorageSystem
from ww1_economy.resources import (
    BuildingType,
    BUILDING_CONFIGS,
    TIER1_BUILDING_TYPES,
    get_config,
    resolve_tier1_production_resource,
)


# ---------------------------------------------------------------------------
# Production report data structures
# ---------------------------------------------------------------------------

@dataclass
class CountryProduction:
    """Aggregated production result for a single country in one monthly tick."""
    country_id:           str
    resources_added:      dict[str, int]  = field(default_factory=dict)
    gold_to_treasury:     float           = 0.0   # Precious Mine gold output
    daily_income_total:   float           = 0.0   # Sum of all building daily incomes
    buildings_processed:  int             = 0
    buildings_skipped:    int             = 0


@dataclass
class ProductionReport:
    """Full monthly production report for a scenario tick."""
    server_id:   str
    scenario_id: str
    by_country:  dict[str, CountryProduction]  = field(default_factory=dict)
    skipped:     list[dict]                    = field(default_factory=list)

    def summary(self) -> dict:
        """Return a JSON-serialisable summary of this report."""
        return {
            "server_id":   self.server_id,
            "scenario_id": self.scenario_id,
            "countries": {
                cid: {
                    "resources_added":     cp.resources_added,
                    "gold_to_treasury":    cp.gold_to_treasury,
                    "daily_income_total":  cp.daily_income_total,
                    "buildings_processed": cp.buildings_processed,
                    "buildings_skipped":   cp.buildings_skipped,
                }
                for cid, cp in self.by_country.items()
            },
            "skipped": self.skipped,
        }


# ---------------------------------------------------------------------------
# ProductionSystem
# ---------------------------------------------------------------------------

class ProductionSystem:
    """
    Runs monthly production ticks for the WW1 economy scenario.

    Parameters
    ----------
    db      : EconomyDB       — shared database instance.
    storage : StorageSystem   — used to add resources to country storage.
    """

    def __init__(self, db: EconomyDB, storage: StorageSystem) -> None:
        self._db      = db
        self._storage = storage

    # ------------------------------------------------------------------
    # Main tick
    # ------------------------------------------------------------------

    def run_monthly_production(
        self,
        server_id:   str,
        scenario_id: str,
    ) -> ProductionReport:
        """
        Execute one in-game month of production for every completed building
        in the scenario.

        Steps
        -----
        1. Fetch all completed buildings (server_id + scenario_id).
        2. For each building:
           a. Look up the BuildingConfig.
           b. Tier 1 — validate province resource matches; skip on mismatch.
           c. Add monthly_production to country storage.
           d. For Precious Mine + gold resource — add gold to treasury report.
           e. Accumulate daily_income for this country.
        3. Return a ProductionReport.

        The caller is responsible for:
          • Depositing ``gold_to_treasury`` values into each country's treasury.
          • Applying ``daily_income_total`` to each country's daily income.
        """
        report    = ProductionReport(server_id=server_id, scenario_id=scenario_id)
        buildings = self._db.get_completed_buildings(server_id, scenario_id)

        for brow in buildings:
            country_id    = brow["country_id"]
            province_id   = brow["province_id"]
            building_type = brow["building_type"]
            resource_type = brow.get("resource_type")   # stored province resource

            cfg = get_config(building_type)

            # Ensure we have a CountryProduction entry
            if country_id not in report.by_country:
                report.by_country[country_id] = CountryProduction(country_id=country_id)
            cp = report.by_country[country_id]

            # ----------------------------------------------------------
            # Tier 1 — resource validation
            # ----------------------------------------------------------
            if cfg.is_tier1:
                if resource_type is None:
                    skip_reason = (
                        f"Tier 1 building '{building_type}' in province "
                        f"'{province_id}' has no resource_type set."
                    )
                    report.skipped.append({
                        "province_id":   province_id,
                        "building_type": building_type,
                        "reason":        skip_reason,
                    })
                    cp.buildings_skipped += 1
                    continue

                if resource_type not in cfg.allowed_resources:
                    skip_reason = (
                        f"Resource mismatch: '{building_type}' in province "
                        f"'{province_id}' has resource_type='{resource_type}' "
                        f"but building allows {sorted(cfg.allowed_resources)}."
                    )
                    report.skipped.append({
                        "province_id":   province_id,
                        "building_type": building_type,
                        "reason":        skip_reason,
                    })
                    cp.buildings_skipped += 1
                    continue

                # Precious Mine: split gold vs gems
                if BuildingType(building_type) == BuildingType.PRECIOUS_MINE:
                    if resource_type == "gold":
                        # Gold → treasury only (not stored)
                        cp.gold_to_treasury += cfg.gold_to_treasury_monthly
                    else:
                        # Gems → storage
                        amount = cfg.monthly_production
                        self._storage.add(
                            server_id, scenario_id, country_id, "gems", amount
                        )
                        cp.resources_added["gems"] = (
                            cp.resources_added.get("gems", 0) + amount
                        )
                else:
                    # Standard Tier 1 — produce province resource
                    prod_resource = resource_type
                    amount        = cfg.monthly_production
                    self._storage.add(
                        server_id, scenario_id, country_id, prod_resource, amount
                    )
                    cp.resources_added[prod_resource] = (
                        cp.resources_added.get(prod_resource, 0) + amount
                    )

            # ----------------------------------------------------------
            # Tier 2 — always valid (no resource dependency)
            # ----------------------------------------------------------
            else:
                if cfg.production_resource is not None:
                    prod_resource = cfg.production_resource
                    amount        = cfg.monthly_production
                    self._storage.add(
                        server_id, scenario_id, country_id, prod_resource, amount
                    )
                    cp.resources_added[prod_resource] = (
                        cp.resources_added.get(prod_resource, 0) + amount
                    )

            # ----------------------------------------------------------
            # Daily income (all building types)
            # ----------------------------------------------------------
            cp.daily_income_total   += cfg.daily_income
            cp.buildings_processed  += 1

        return report

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    def get_country_income_from_buildings(
        self,
        server_id:   str,
        scenario_id: str,
        country_id:  str,
    ) -> float:
        """
        Calculate the total daily income from all completed buildings owned
        by a country, without running a full production tick.
        """
        total = 0.0
        for row in self._db.get_buildings_by_country(server_id, scenario_id, country_id):
            if row["is_completed"]:
                cfg    = get_config(row["building_type"])
                total += cfg.daily_income
        return round(total, 4)

    def get_monthly_production_preview(
        self,
        server_id:   str,
        scenario_id: str,
        country_id:  str,
    ) -> dict:
        """
        Return a preview of what would be produced next month for a country,
        without writing anything to the database.
        """
        preview: dict[str, int]  = {}
        gold_income: float       = 0.0
        daily_income: float      = 0.0

        for row in self._db.get_buildings_by_country(server_id, scenario_id, country_id):
            if not row["is_completed"]:
                continue
            cfg            = get_config(row["building_type"])
            resource_type  = row.get("resource_type")
            daily_income  += cfg.daily_income

            if cfg.is_tier1:
                if resource_type and resource_type in cfg.allowed_resources:
                    if BuildingType(row["building_type"]) == BuildingType.PRECIOUS_MINE:
                        if resource_type == "gold":
                            gold_income += cfg.gold_to_treasury_monthly
                        else:
                            preview["gems"] = preview.get("gems", 0) + cfg.monthly_production
                    else:
                        preview[resource_type] = (
                            preview.get(resource_type, 0) + cfg.monthly_production
                        )
            else:
                if cfg.production_resource:
                    preview[cfg.production_resource] = (
                        preview.get(cfg.production_resource, 0) + cfg.monthly_production
                    )

        return {
            "country_id":          country_id,
            "monthly_resources":   preview,
            "gold_to_treasury":    gold_income,
            "daily_income_total":  round(daily_income, 4),
        }
